baseURL = 'http://localhost:1314/'
languageCode = 'en-us'
title = 'MindFull Documentation'
theme = 'hugo-book'

[params]
  # (Optional) Hugo Book config
  BookLogo = 'logo.png'
  BookSearch = true
  BookSectionEnumerable = true

[[module.mounts]]
  source = 'content'
  target = 'content'

[[module.mounts]]
  source = '../_docs_src'
  target = 'content/docs'